### ISSUE TITLE
Unhandled exception when EvKit is powered down.

### ISSUE THREAD

**Issue by kevin-gillespie** [Analog-Devices-MSDK/MAX-BLE-HCI#28]
I'm guessing that the USB to UART adapter is picking up some junk when the attached kit powers down.
```
>>> Exception in thread Thread-DUT:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kgills/Workspace/MAX-BLE-HCI/src/max_ble_hci/_transport.py", line 357, in _read
    data_len = read_data[1]
IndexError: index out of range
```

**Comment by EricB-ADI** [comment]
fixed in #32
